AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures:
      - x86_64
    Timeout: 30
    Tracing: Active

Resources:
  AspNetFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 935833345960.dkr.ecr.eu-west-1.amazonaws.com/apprunner-ecr-repo:0.0.5
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"